name = "KAT: RFC 5649 AES-192 KEK"
description = "Known-Answer Test: RFC 5649 key wrap with padding with 192-bit KEK, 128-bit plaintext"

[[steps]]
operation = "Import"
request = "step1_import_key.json"
assert_success = true

[steps.capture]
key_id = "UniqueIdentifier"

[[steps]]
operation = "Encrypt"
request = "step2_wrap.json"
assert_success = true

[steps.assert_fields]
Data = "5FD7477FDC165910C8E5DD891A421B10DB10362FD293B128"

[[steps]]
operation = "Decrypt"
request = "step3_decrypt.json"
assert_success = true
[steps.assert_fields]
Data = "00112233445566778899AABBCCDDEEFF"
