# Multi-factor: JWT + API Token from authentication.md (updated idp_auth format)
[idp_auth]
jwt_auth_provider = ["https://accounts.google.com,https://www.googleapis.com/oauth2/v3/certs,"]

[http]
api_token_id = "test-symmetric-key-id"
