default_username = "admin"

[http]
port = 10000
hostname = "0.0.0.0"

[db]
database_type = "sqlite"
sqlite_path = "/tmp/kms-data"
clear_database = false
unwrapped_cache_max_age = 15

[tls]
# FIPS images use PEM cert + key
tls_cert_file = "/data/certificates/client_server/server/kmserver.acme.com.crt"
tls_key_file = "/data/certificates/client_server/server/kmserver.acme.com.key"
clients_ca_cert_file = "/data/certificates/client_server/ca/ca.crt"
# Restrict to TLS1.3 suites so TLS1.2 handshakes get rejected on this port.
tls_cipher_suites = "TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256"

[socket_server]
socket_server_start = true
socket_server_port = 5697
socket_server_hostname = "0.0.0.0"

[logging]
rust_log = "info,cosmian_kms=info"
ansi_colors = false

[ui_config]
ui_index_html_folder = "/usr/local/cosmian/ui/dist"
