name = "KMIP 1.2 RNGRetrieve"
description = "Retrieve random bytes using KMIP 1.2"
wire_format = "binary"
kmip_version = [1, 2]

[[steps]]
operation = "RNGRetrieve"
request = "step1_rng.json"
assert_success = true
