#!/usr/bin/env bash
# provision.sh — Bootstrap AppRole credentials for the SPIRE integration test stack.
#
# Called by `mise run test:spire` after vault-proxy is healthy.
# Connects to vault-proxy at VAULT_ADDR (default: https://localhost:8200).
#
# What it does:
#   1. Obtain an admin token from auth-verifier via vault-proxy.
#   2. Create AppRole "spire-server"   -- dedicated role for SPIRE UpstreamAuthority.
#   3. Create AppRole "mistral-agents" -- dedicated role for Mistral AI agents.
#   4. Generate secret-IDs for both roles.
#   5. Write credentials to SECRETS_ENV_FILE for use by the mise task.
#
# Environment:
#   VAULT_ADDR        -- default: https://localhost:8200
#   VAULT_CACERT      -- path to CA cert; default: test_data/spire/certs/ca.crt
#   ADMIN_USER        -- auth-verifier admin username; default: admin
#   ADMIN_PASS        -- auth-verifier admin password; default: AdminPassword123!
#   SECRETS_ENV_FILE  -- output file path; default: /tmp/spire-secrets.env

set -euo pipefail

VAULT_ADDR="${VAULT_ADDR:-https://localhost:8200}"
VAULT_CACERT="${VAULT_CACERT:-test_data/spire/certs/ca.crt}"

ADMIN_USER="${ADMIN_USER:-admin}"
ADMIN_PASS="${ADMIN_PASS:-AdminPassword123!}"

SECRETS_ENV_FILE="${SECRETS_ENV_FILE:-/tmp/spire-secrets.env}"

log() { echo "[provision] $*"; }

# ── 1. Obtain admin token ─────────────────────────────────────────────────────
log "Obtaining admin token from auth-verifier..."
ADMIN_TOKEN=$(curl -sf \
  --cacert "${VAULT_CACERT}" \
  -X POST \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"${ADMIN_USER}\",\"password\":\"${ADMIN_PASS}\"}" \
  "${VAULT_ADDR}/v1/auth/userpass/login/${ADMIN_USER}" \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['auth']['client_token'])")
log "Admin token obtained."

vault_api() {
  local method="$1"; local path="$2"; shift 2
  curl -sf \
    --cacert "${VAULT_CACERT}" \
    -X "${method}" \
    -H "X-Vault-Token: ${ADMIN_TOKEN}" \
    -H "Content-Type: application/json" \
    "$@" \
    "${VAULT_ADDR}${path}"
}

# ── 2. Create AppRole: spire-server ──────────────────────────────────────────
log "Creating AppRole 'spire-server'..."
vault_api POST /v1/auth/approle/role/spire-server -d '{
  "token_ttl":          "1h",
  "token_max_ttl":      "4h",
  "token_policies":     ["default"],
  "secret_id_ttl":      "0",
  "secret_id_num_uses": 0
}' > /dev/null

SPIRE_ROLE_ID=$(vault_api GET /v1/auth/approle/role/spire-server/role-id \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['data']['role_id'])")
log "spire-server role_id: ${SPIRE_ROLE_ID}"

SPIRE_SECRET_ID=$(vault_api POST /v1/auth/approle/role/spire-server/secret-id \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['data']['secret_id'])")
log "spire-server secret_id obtained."

# ── 3. Create AppRole: mistral-agents ────────────────────────────────────────
log "Creating AppRole 'mistral-agents'..."
vault_api POST /v1/auth/approle/role/mistral-agents -d '{
  "token_ttl":          "1h",
  "token_max_ttl":      "4h",
  "token_policies":     ["default"],
  "secret_id_ttl":      "0",
  "secret_id_num_uses": 0
}' > /dev/null

MISTRAL_ROLE_ID=$(vault_api GET /v1/auth/approle/role/mistral-agents/role-id \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['data']['role_id'])")
log "mistral-agents role_id: ${MISTRAL_ROLE_ID}"

MISTRAL_SECRET_ID=$(vault_api POST /v1/auth/approle/role/mistral-agents/secret-id \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['data']['secret_id'])")
log "mistral-agents secret_id obtained."

# ── 4. Transit smoke test ─────────────────────────────────────────────────────
log "Transit smoke test: listing transit keys..."
TRANSIT_LIST=$(vault_api GET /v1/transit/keys 2>/dev/null || echo "{}")
log "Transit response: ${TRANSIT_LIST:0:80}..."

# ── 5. Write credentials to env file ─────────────────────────────────────────
log "Writing credentials to ${SECRETS_ENV_FILE}..."
cat > "${SECRETS_ENV_FILE}" <<EOF
# Generated by provision.sh -- source this file to inject AppRole credentials.
# DO NOT COMMIT -- contains test secrets.
export APPROLE_ROLE_ID="${SPIRE_ROLE_ID}"
export APPROLE_SECRET_ID="${SPIRE_SECRET_ID}"
export MISTRAL_ROLE_ID="${MISTRAL_ROLE_ID}"
export MISTRAL_SECRET_ID="${MISTRAL_SECRET_ID}"
EOF
chmod 600 "${SECRETS_ENV_FILE}"

log ""
log "=== Provisioning complete ==="
log "  SPIRE AppRole role_id:   ${SPIRE_ROLE_ID}"
log "  Mistral AppRole role_id: ${MISTRAL_ROLE_ID}"
log "  Credentials written to:  ${SECRETS_ENV_FILE}"
log "  PKI CA key must already exist in KMS with tag: vault_pki_ca"
